# Generated by Django 3.2.4 on 2021-07-03 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0002_auto_20210702_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='lessons_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
