# Generated by Django 3.2.4 on 2021-07-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_lesson_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='students',
            new_name='student',
        ),
    ]
