# Generated by Django 3.2.4 on 2021-07-10 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='module',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='updated_on_on',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='updated_on_on',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='updated_on_on',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='updated_on_on',
            new_name='updated_on',
        ),
        migrations.AlterField(
            model_name='unit',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='languages.lesson'),
        ),
    ]
