# Generated by Django 3.2.4 on 2021-07-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20210710_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='language',
            new_name='lesson',
        ),
    ]
