# Generated by Django 3.2.4 on 2021-08-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
    ]
