# Generated by Django 3.2.4 on 2021-08-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_remove_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
