# Generated by Django 3.2.4 on 2021-08-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
