# Generated by Django 3.2.4 on 2021-08-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
