# Generated by Django 4.0.1 on 2022-01-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0009_alter_file_creator_alter_image_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
