# Generated by Django 4.0.1 on 2022-01-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0010_language_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, default=None),
        ),
    ]
