# Generated by Django 4.0.1 on 2022-01-16 01:27

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0011_rename_file_video_video_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=None, verbose_name='videos'),
        ),
    ]
