# Generated by Django 3.2.4 on 2021-07-05 03:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
                ('published_posts', django.db.models.manager.Manager()),
            ],
        ),
    ]
