# Generated by Django 3.2.4 on 2021-07-05 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
            ],
        ),
    ]
